  // File generated by FlutterFire CLI.
  // ignore_for_file: type=lint
  import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
  import 'package:flutter/foundation.dart'
      show defaultTargetPlatform, kIsWeb, TargetPlatform;

  /// Default [FirebaseOptions] for use with your Firebase apps.
  ///
  /// Example:
  /// ```dart
  /// import 'firebase_options.dart';
  /// // ...
  /// await Firebase.initializeApp(
  ///   options: DefaultFirebaseOptions.currentPlatform,
  /// );
  /// ```
  class DefaultFirebaseOptions {
    static FirebaseOptions get currentPlatform {
      if (kIsWeb) {
        return web;
      }
      switch (defaultTargetPlatform) {
        case TargetPlatform.android:
          return android;
        case TargetPlatform.iOS:
          return ios;
        case TargetPlatform.macOS:
          return macos;
        case TargetPlatform.windows:
          return windows;
        case TargetPlatform.linux:
          throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for linux - '
            'you can reconfigure this by running the FlutterFire CLI again.',
          );
        default:
          throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.',
          );
      }
    }

    static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyDYpOLFZndLfbppmHSNtg_pUoKyFqQrlXU',
      appId: '1:58922100698:web:9323b6598391ac4e1002e3',
      messagingSenderId: '58922100698',
      projectId: 'ycprms-ab68e',
      authDomain: 'ycprms-ab68e.firebaseapp.com',
      storageBucket: 'ycprms-ab68e.firebasestorage.app',
      measurementId: 'G-E102EF6900',
    );

    static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyDCp2aSZ-zWgvzc00pChx7es2jvMNjlGxg',
      appId: '1:58922100698:android:770791d7864bd5441002e3',
      messagingSenderId: '58922100698',
      projectId: 'ycprms-ab68e',
      storageBucket: 'ycprms-ab68e.firebasestorage.app',
    );

    static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyChT8LE3fooexVMphoJc_yEszqdio2QrIE',
      appId: '1:58922100698:ios:363d0d24923343441002e3',
      messagingSenderId: '58922100698',
      projectId: 'ycprms-ab68e',
      storageBucket: 'ycprms-ab68e.firebasestorage.app',
      iosBundleId: 'com.example.yangChow',
    );

    static const FirebaseOptions macos = FirebaseOptions(
      apiKey: 'AIzaSyChT8LE3fooexVMphoJc_yEszqdio2QrIE',
      appId: '1:58922100698:ios:363d0d24923343441002e3',
      messagingSenderId: '58922100698',
      projectId: 'ycprms-ab68e',
      storageBucket: 'ycprms-ab68e.firebasestorage.app',
      iosBundleId: 'com.example.yangChow',
    );

    static const FirebaseOptions windows = FirebaseOptions(
      apiKey: 'AIzaSyDYpOLFZndLfbppmHSNtg_pUoKyFqQrlXU',
      appId: '1:58922100698:web:8808984b6bccdf761002e3',
      messagingSenderId: '58922100698',
      projectId: 'ycprms-ab68e',
      authDomain: 'ycprms-ab68e.firebaseapp.com',
      storageBucket: 'ycprms-ab68e.firebasestorage.app',
      measurementId: 'G-7Q6N91PFKE',
    );
  }
